### PR TITLE
Add section in README for trouble shooting "user_i2c_write: Remote I/…

### PR DESCRIPTION
**Pull request by Gfast2**
Awesome codebase, enlight my day for chrismas, hopefully this tiny complement for troubleshooting section will help out guys like me (the one who plays some IoT in free time, or a "new :bee: " for short) have less time to jump-start.

Thanks again for sharing the code & hope you guys have nice day for the rest of the year.

:christmas_tree: :beers: :beers: :beers: :christmas_tree: 

Su

### CODE REVIEW

**Review by FelosRG — APPROVED** [review]
I had solved my problem with this suggestion,  it would have been nice if this information had been visible in the README

**Comment by flipthedog** [comment]
This is needed to make this library work on Raspberry Pi 4 Model B. +1

**Comment by bsimmo** [comment]
> This is needed to make this library work on Raspberry Pi 4 Model B. +1

It's the not Pi. It's the BME680 you are using. They, like the BME280, have two I2C addresses, and you can switch between them.
It's in the BME/BSEC documentation that _should be read_ along side this compiling part that creates readable output for Python code. 

Although having it in the readme is always a good idea. Say under FAQ's
In the same way you should change the timezone and you can alter the output or eCO2 etc.

**Comment by alexh-name** [comment]
Thanks! Just changed some language and formatting.

**Pull request merged**
